# Generated by Django 5.1 on 2024-11-12 06:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scalping', '0002_alter_tradingrecord_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinScalpingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='분석 시간')),
                ('coin_symbol', models.CharField(max_length=20, verbose_name='코인 심볼')),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='현재 가격')),
                ('volume_24h', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='24시간 거래량')),
                ('price_change_24h', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='24시간 변동률(%)')),
                ('scalping_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='스캘핑 점수')),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], max_length=10, verbose_name='우선순위')),
                ('analysis', models.TextField(verbose_name='분석 결과')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['coin_symbol'], name='scalping_co_coin_sy_91f131_idx'), models.Index(fields=['priority'], name='scalping_co_priorit_d006c9_idx')],
            },
        ),
    ]
