# Generated by Django 5.1 on 2024-11-13 01:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scalping', '0003_coinscalpinganalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingrecord',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='tradingrecord',
            name='scalping_tr_timesta_375033_idx',
        ),
        migrations.RemoveField(
            model_name='tradingrecord',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='tradingrecord',
            name='avg_buy_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='평균 매수가'),
        ),
        migrations.AddField(
            model_name='tradingrecord',
            name='exchange',
            field=models.CharField(choices=[('UPBIT', 'Upbit'), ('BINANCE', 'Binance')], default='UPBIT', max_length=10, verbose_name='거래소'),
        ),
        migrations.AddField(
            model_name='tradingrecord',
            name='technical_indicators',
            field=models.JSONField(default=dict, verbose_name='기술적 지표'),
        ),
        migrations.AlterField(
            model_name='tradingrecord',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='보유 자산'),
        ),
        migrations.AlterField(
            model_name='tradingrecord',
            name='trade_amount_krw',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='거래 금액'),
        ),
        migrations.AddIndex(
            model_name='tradingrecord',
            index=models.Index(fields=['created_at'], name='scalping_tr_created_0466d9_idx'),
        ),
    ]
