# Generated by Django 5.1 on 2024-11-13 02:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scalping', '0004_alter_tradingrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingrecord',
            name='trade_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8, verbose_name='거래 비율(%)'),
        ),
    ]
