databases:
  - name: gridtrader_db
    plan: free
    databaseName: gridtrader
    user: hanvit
    region: singapore

services:
  - type: web
    plan: free
    name: gridtrader_backend
    runtime: python
    region: singapore
    buildCommand: "./build.sh && python manage.py collectstatic --noinput"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gridtrader_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4