# Generated by Django 5.1 on 2024-08-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('gateway_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('offset', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('traded', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('gateway_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100, unique=True)),
                ('vt_symbol', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('parameters', models.JSONField()),
                ('variables', models.JSONField()),
            ],
        ),
    ]
