# Generated by Django 5.1 on 2024-08-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=20)),
                ('result_string', models.TextField()),
                ('current_price', models.FloatField()),
                ('price_prediction', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('selected_strategy', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
