# Generated by Django 5.1 on 2024-08-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='price_prediction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
