# Generated by Django 5.1 on 2024-08-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_analysisresult_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='result_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
