# Generated by Django 5.1 on 2024-08-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_alter_analysisresult_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='korean_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
