# Generated by Django 5.1 on 2024-12-19 06:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_analysisresult_analysis_results_1hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('korean_summary', models.TextField(blank=True, null=True)),
                ('result_string', models.TextField(blank=True, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='현재 가격')),
                ('price_prediction', models.CharField(blank=True, max_length=10, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('selected_strategy', models.CharField(max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], default='HOLD', max_length=4, verbose_name='거래 유형')),
                ('trade_amount_krw', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='거래 금액')),
                ('coin_balance', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20, verbose_name='코인 보유량')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='보유 자산')),
                ('avg_buy_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='평균 매수가')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
