# Generated by Django 5.1 on 2025-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='trade_type',
            field=models.CharField(default='HOLD', max_length=20, verbose_name='거래 유형'),
        ),
    ]
