# Generated by Django 5.1 on 2024-08-28 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanaceAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('futures_balance', models.JSONField()),
                ('futures_positions', models.JSONField()),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.RemoveField(
            model_name='futurebalance',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='binancefuturesaccount',
            name='futurebalance',
        ),
        migrations.DeleteModel(
            name='BinanceAccount',
        ),
        migrations.DeleteModel(
            name='SpotBalance',
        ),
        migrations.DeleteModel(
            name='BinanceFuturePosition',
        ),
        migrations.DeleteModel(
            name='BinanceFuturesAccount',
        ),
        migrations.DeleteModel(
            name='FutureBalance',
        ),
    ]
