# Generated by Django 5.1 on 2024-12-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingrecord',
            name='symbol',
        ),
        migrations.AddField(
            model_name='tradingrecord',
            name='symbols',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
