# Generated by Django 5.1 on 2024-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceData', '0002_remove_tradingrecord_symbol_tradingrecord_symbols'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceTradingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('long_symbols', models.JSONField(blank=True, default=list)),
                ('short_symbols', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
